### ISSUE TITLE
Emergency Todo:

### ISSUE THREAD

**Issue by FlavoredCactus** [LLA-Gaming/SS13#407]
These should be done before another "hotfix"
## Betrayal Gamemode
- [x] - Make a separate traitor preference for betrayal
- [x] - Fix TC bug, Cap TCs at 12
- [x] - Give 1 additional TC to start with
- [x] - Make the round end when every betrayed agent dies

## Honking Angels
- [x] - fix vision on the shuttle
- [x] - Remove Wall smashing
- [x] - Give angel's xray/thermals
- [x] - Give a blink that hurts them to use

## Mind's bar
- [x] - Approve or Deny mindtrixx's bar ( https://github.com/LLA-Gaming/SS13/pull/406 )

## Other
- [x] - Allow players to modify their preferences outside the lobby
- [x] - AFK don't count in OOC votes (and votes play a sound)
