### ISSUE TITLE
Ahbahl's TODO list

### ISSUE THREAD

**Issue by Ahbahl** [LLA-Gaming/SS13#489]
- [x] Add a chemical overlay and a host health overlay to borers 
- [x] Add more names for borers
- [x] Remove "me" verb from borers
- [x] Give borers a "rapid suction" verb to gain chems faster in exchange for some of the hosts nutriments 
- [x] Make the "lay egg" verb use a timer instead of chemicals 
- [x] Give the borer a new verb to lay a "nest" that removes the need for plasma in the air for eggs to hatch (costs 200 chems) 
- [x] Make borers able to infest a few other mobs besides humans 
- [x] Add a nonlethal way to contain borers 
- [x] Add an upgrade menu for borers 
- [x] Add stuff for the upgrade menu
